# Generated by Django 6.0.3 on 2026-08-09 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('is_paid_plan', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('schema_created', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public.tenants',
                'ordering': ['-created_on'],
            },
        ),
    ]
