# Generated by Django 6.0.3 on 2026-08-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=60, null=True, unique=True),
        ),
    ]
